import TemplatesAbout from '@/components/templates/About';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'about',
  description: 'Generated by create next app',
};

const About = () => {
  return <TemplatesAbout />;
};

export default About;
