import TemplatesIndex from '@/components/templates/Index';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'top',
  description: 'Generated by create next app',
};

const Index = () => {
  return <TemplatesIndex />;
};

export default Index;
